logging:
  level: INFO
  format: "%(asctime)s - %(levelname)-8s - %(threadName)-10s - %(name)s - %(message)s"
mqtt:
  host: 192.168.1.2
  port: 1883
  protocol: 5
  username: mqtt_user
  password: mqtt_pass
nibe:
  model: F1255
  nibegw:
    ip: 192.168.1.3
    listening_port: 9999
    read_port: 10000
    write_port: 10001
  poll:
    interval: 30
    coils:
      - bt50-room-temp-s1-40033
      - bt1-outdoor-temperature-40004
      - bt7-hw-top-40013
      - bt6-hw-load-40014
      - temporary-lux-48132
      - hot-water-high-power-mode-48743
      - eb100-ep14-bt3-return-temp-40012
      - bt2-supply-temp-s1-40008
      - compressor-frequency-actual-43136
      - compressor-starts-eb100-ep14-43416
      - degree-minutes-16-bit-43005
      - prio-43086
      - passive-cool-shunt-44753
      - status-cooling-43024
      - tot-op-time-compr-eb100-ep14-43420
      - tot-hw-op-time-compr-eb100-ep14-43424
      - int-el-add-power-43084
      - tot-op-time-add-43081
      - heat-meter-hw-cpr-and-add-ep14-44298
      - heat-meter-heat-cpr-and-add-ep14-44300
      - eb100-ep14-bt11-brine-out-temp-40016
      - eb100-ep14-bt10-brine-in-temp-40015
      - ep14-gp2-brine-pump-status-ep14-43439
      - supply-pump-speed-ep14-43437
      - hwc-pump-status-gp11-43180
      - heat-offset-s1-47011
      - cool-offset-s1-48739
      - allow-additive-heating-47370
      - holiday-activated-48043
      - allow-heating-47371
      - allow-cooling-47372
      - hw-comfort-48120
      - ground-water-pump-accessory-47327
      - eq1-bt64-cool-supply-temp-40045
      - eq1-bt65-cool-return-temp-40046
      - calc-cooling-supply-s1-44270
